In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import pandas as pd

In [50]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

In [51]:
iris=load_iris()

In [52]:
l1=cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)
print(l1)
l1_score=np.average(l1)
print(l1_score)

[0.98 0.96 0.98]
0.9733333333333333


C:\Users\abhav\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [53]:
l2=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=3)
print(l2)
l2_score=np.average(l2)
print(l2_score)

[0.98 0.94 0.96]
0.96


In [54]:
l3=cross_val_score(SVC(),iris.data,iris.target,cv=3)
print(l3)
l3_score=np.average(l3)
print(l3_score)

[0.96 0.98 0.94]
0.96


In [55]:
l4=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)
print(l4)
l4_score=np.average(l4)
print(l4_score)

[0.98 0.94 0.98]
0.9666666666666667


### Best score so far is for the algorithm LogisticRegression