In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [3]:
x=load_digits()

In [4]:
dir(x)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
X=x.data
y=x.target

In [8]:
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [11]:
len(X_train)

1437

In [12]:
len(X_test)

360

In [13]:
from sklearn.svm import SVC

In [14]:
model=SVC(kernel='linear')

In [15]:
model.fit(X_train,y_train)

SVC(kernel='linear')

In [16]:
model.predict(X_test)

array([6, 9, 1, 6, 7, 8, 1, 8, 5, 9, 2, 3, 2, 5, 3, 6, 6, 4, 0, 7, 4, 5,
       6, 0, 0, 4, 9, 4, 2, 1, 8, 1, 4, 3, 6, 0, 1, 2, 7, 8, 0, 3, 4, 5,
       6, 4, 2, 2, 0, 7, 4, 1, 4, 6, 4, 4, 8, 4, 5, 4, 0, 5, 4, 0, 2, 6,
       0, 1, 8, 5, 1, 4, 9, 6, 8, 6, 1, 7, 7, 0, 9, 8, 3, 6, 6, 7, 3, 4,
       5, 3, 3, 4, 7, 6, 3, 2, 6, 8, 3, 6, 7, 0, 7, 3, 0, 7, 1, 1, 6, 1,
       4, 9, 3, 5, 4, 1, 2, 3, 4, 4, 9, 7, 2, 3, 9, 1, 3, 9, 0, 4, 0, 5,
       7, 1, 9, 7, 5, 6, 2, 1, 6, 9, 8, 0, 7, 9, 7, 9, 3, 7, 5, 1, 5, 8,
       8, 4, 7, 2, 0, 0, 0, 0, 7, 7, 2, 7, 4, 2, 1, 0, 5, 8, 7, 5, 4, 8,
       2, 9, 5, 2, 8, 6, 0, 4, 1, 7, 0, 8, 7, 3, 7, 7, 2, 5, 9, 8, 3, 0,
       5, 4, 5, 7, 9, 3, 9, 4, 7, 0, 9, 4, 1, 1, 2, 0, 3, 5, 8, 7, 7, 0,
       4, 1, 9, 8, 1, 6, 6, 1, 0, 0, 6, 0, 8, 5, 5, 7, 5, 0, 7, 5, 6, 7,
       6, 7, 5, 5, 5, 0, 0, 5, 6, 5, 0, 2, 3, 4, 1, 9, 8, 4, 2, 8, 5, 2,
       8, 9, 5, 3, 6, 7, 0, 2, 6, 2, 1, 5, 8, 9, 1, 4, 6, 1, 1, 6, 0, 9,
       4, 2, 1, 4, 1, 5, 7, 0, 5, 2, 3, 6, 2, 5, 4,

In [17]:
model.score(X_test,y_test)

0.9916666666666667

## For RBF

In [22]:
model_new=SVC(kernel='rbf')

In [23]:
model_new.fit(X_train,y_train)

SVC()

In [24]:
model.predict(X_test)

array([6, 9, 1, 6, 7, 8, 1, 8, 5, 9, 2, 3, 2, 5, 3, 6, 6, 4, 0, 7, 4, 5,
       6, 0, 0, 4, 9, 4, 2, 1, 8, 1, 4, 3, 6, 0, 1, 2, 7, 8, 0, 3, 4, 5,
       6, 4, 2, 2, 0, 7, 4, 1, 4, 6, 4, 4, 8, 4, 5, 4, 0, 5, 4, 0, 2, 6,
       0, 1, 8, 5, 1, 4, 9, 6, 8, 6, 1, 7, 7, 0, 9, 8, 3, 6, 6, 7, 3, 4,
       5, 3, 3, 4, 7, 6, 3, 2, 6, 8, 3, 6, 7, 0, 7, 3, 0, 7, 1, 1, 6, 1,
       4, 9, 3, 5, 4, 1, 2, 3, 4, 4, 9, 7, 2, 3, 9, 1, 3, 9, 0, 4, 0, 5,
       7, 1, 9, 7, 5, 6, 2, 1, 6, 9, 8, 0, 7, 9, 7, 9, 3, 7, 5, 1, 5, 8,
       8, 4, 7, 2, 0, 0, 0, 0, 7, 7, 2, 7, 4, 2, 1, 0, 5, 8, 7, 5, 4, 8,
       2, 9, 5, 2, 8, 6, 0, 4, 1, 7, 0, 8, 7, 3, 7, 7, 2, 5, 9, 8, 3, 0,
       5, 4, 5, 7, 9, 3, 9, 4, 7, 0, 9, 4, 1, 1, 2, 0, 3, 5, 8, 7, 7, 0,
       4, 1, 9, 8, 1, 6, 6, 1, 0, 0, 6, 0, 8, 5, 5, 7, 5, 0, 7, 5, 6, 7,
       6, 7, 5, 5, 5, 0, 0, 5, 6, 5, 0, 2, 3, 4, 1, 9, 8, 4, 2, 8, 5, 2,
       8, 9, 5, 3, 6, 7, 0, 2, 6, 2, 1, 5, 8, 9, 1, 4, 6, 1, 1, 6, 0, 9,
       4, 2, 1, 4, 1, 5, 7, 0, 5, 2, 3, 6, 2, 5, 4,

In [25]:
model.score(X_test,y_test)

0.9916666666666667