In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("homeprices multi.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

## Data Preprocessing

In [8]:
import math
median=math.floor(df.bedrooms.median())
median

4

In [11]:
df.bedrooms=df.bedrooms.fillna(median)

## Data Training

In [20]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [21]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [22]:
reg.intercept_

221323.0018654043

In [24]:
reg.predict([[2600,3,20]])

array([518217.63297611])

## How it has calculated the price

In [27]:
y=reg.coef_[0]*2600+reg.coef_[1]*3+reg.coef_[2]*20+reg.intercept_

In [28]:
y

518217.6329761124

In [30]:
reg.predict([[2500,4,5]])

array([578876.03748933])